name: Update Activity Graph

on:
  schedule: # execute every Friday at 00:30 UTC
    - cron: "30 0 * * 5"
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    permissions:
      contents: write

    steps:
      - uses: actions/checkout@v7

      - name: Generate activity graph
        uses: maurodesouza/github-readme-activity-graph-action@v1
        with:
          username: ${{ github.repository_owner }}
          options: theme=rogue&custom_title=GitHub%20Contribution%20Graph&title_color=ff6e96
          output_path: assets/activity-graph.svg
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Push activity-graph.svg to the output branch
        uses: stefanzweifel/git-auto-commit-action@v7
        with:
          commit_message: "Update GitHub activity graph"
          file_pattern: assets/activity-graph.svg
